### ISSUE TITLE
UndefinedFunctionError Braintree.fetch_env!/1 not found

### ISSUE THREAD

**Issue by ahd-elang** [sorentwo/braintree-elixir#118]
When calling Braintree.Webhook.Validation.validate_signature/2 I got this error because Braintree.fetch_env! doesn't exist. 
```
     ** (UndefinedFunctionError) function Braintree.fetch_env!/1 is undefined or private. Did you mean one of:
     
           * get_env/1
           * get_env/2
```
Braintree.get_env actually throw error when env not found, so I think changing it to get_env/1 will fix it

**Comment by sorentwo** [comment]
Closed with #119
