### ISSUE TITLE
New Release With Plan Functionality?

### ISSUE THREAD

**Issue by bsvec** [sorentwo/braintree-elixir#152]
We are in the process of implementing subscription billing in our application and I see that there was a PR merged back in May (#146) that adds the ability to create and update Braintree Plans.  It would be really useful to us to be able to use that functionality but there hasn't been a new release of the Hex package since that PR was merged.

Would it be possible to make a new release sometime soon? 

Failing that, we may want to reference a specific commit in our `mix.exs` to get this capability, but are there any reasons that we **shouldn't** rely on the code in `master` currently?  Are there breaking changes in `master` relative to version `0.12.1`?

Thanks!

**Comment by sorentwo** [comment]
Thanks for the prompt! Published as [v0.13.0](https://github.com/sorentwo/braintree-elixir/releases/tag/v0.13.0) 💛
