### ISSUE TITLE
Complete API Support

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/braintree-elixir#17]
The only barrier to releasing 1.0 is full support for the Braintree API. Below is a list of the missing and in-progress features, according to the online reference for Ruby.
- [x] Add-On
  - [x] All
- [x] Address
  - [x] Create
  - [x] Delete
  - [x] Find
  - [x] Update
- [x] CreditCardVerification
  - [x] Search
- [x] Customer
  - [x] Create
  - [x] Update
  - [x] Delete
  - [x] Find
  - [x] Search
- [x] Discount
  - [x] All
- [x] Merchant Account
  - [x] Create
  - [x] Find
  - [x] Update
- [x] Settlement Batch Summary
  - [x] Generate
- [x] Subscription
  - [x] Cancel
  - [x] Create
  - [x] Find
  - [x] Retry Charge
  - [x] Search
  - [x] Update

**Comment by samueljseay** [comment]
I'd like to help out with this where I can :)

**Comment by sorentwo** [comment]
@samueljseay submit whatever you like, PRs are definitely appreciated!

**Comment by samueljseay** [comment]
#22

**Comment by sorentwo** [comment]
Merchant account and address support have been merged in, getting much closer!

**Comment by sorentwo** [comment]
All features supported thanks to @feda12! We need some cleanup before an RC can be released, but getting so close. 🎉
