### ISSUE TITLE
Token version is not the same as Braintree libs

### ISSUE THREAD

**Issue by AdamBrodzinski** [sorentwo/braintree-elixir#18]
This library returns the version 1 token by default while the other libraries will return version 2 by default. I ran into several issues trying to figure out why my token wasn't working since the Braintree docs are very vague and sparse.

https://github.com/braintree/braintree_ruby/blob/c35917379a33de405b7a47eb9f83b7f732255262/lib/braintree/client_token.rb#L5

https://developers.braintreepayments.com/reference/request/client-token/generate/node#version

Would you want to change the library to follow suite? I can PR if that's something that's wanted. At the least I think we should document that it defaults to version 1 of the token.

*edit*

**Comment by sorentwo** [comment]
@AdamBrodzinski Thanks for tracking this down. I'd welcome documentation about the token version _at the very least_. Ideally I'd like the version to be configurable, and for the new default to be 2. If you are up for that I'd welcome a PR, otherwise I'll try and get to it.

**Comment by AdamBrodzinski** [comment]
@sorentwo sounds good. I can at the very least PR docs/readme for the token version but can also take a crack at editing the code this weekend.

Thanks again for this lib! 👍
