### ISSUE TITLE
Occasional {:error, ":closed"} errors for API calls

### ISSUE THREAD

**Issue by nauger** [sorentwo/braintree-elixir#20]
I brought this up previously in an unrelated GH issue, but wanted to re-surface incase anyone else using this library might have additional insight.

Every once in awhile (every few days) we'll see calls fail with a match error on:

```
{:error, ":closed"}
```

I've attempted to tune-down our pool by creating a special pool for braintree-elixir:

```
:hackney_pool.child_spec(:braintree_elixir_pool, [timeout: 30000, max_connections: 10])
```

Which I then use in this branch:

https://github.com/revzilla/braintree-elixir/commit/e6c99e88e01971228c56705d1347048e8f98c37f

Unfortunately, we still see this error on occasion.  I've reached out to Braintree support, and while they won't support an unofficial library directly, they did mention that their official braintree libraries do NOT pool connections or keep sockets open (but that if we did, they'd recommend to close after 50 seconds at most.)

Given that, should the default be to NOT pool braintree connections?

Thoughts?

**Comment by sorentwo** [comment]
@nauger pardon the slow reply, I've been on vacation for a bit.

I've had the chance to think about this for a while, and I don't think the pooling is responsible for your closed connections. It makes sense that Braintree wouldn't pool connections in their official libraries, none of them need the same level of parallelism that is standard in an Erlang/Elixir app. Pooling is the default for most Erlang libraries, and virtually every API client in Elixir has been built on Hackney, either directly or via HTTParty. It doesn't seem to be a widespread error, which leads me to believe it's something else.

If you'd like to try disabling the pool entirely you can do so with a configuration option. From the documentation:

>Note: Sometimes you want to disable the default pool in your app without having to set the client option each time. You can now do this by setting the hackney application environment key use_default_pool to false.

Having said all that, I think exposing the Hackney options directly is a good idea. I can't use the implementation from your commit, though. It is using an older version that still used HTTParty, which has been removed.

**Comment by sorentwo** [comment]
Option support has been added with c42e48a

**Comment by nauger** [comment]
Thanks @sorentwo!  Our app hits a handful of 3rd party HTTP/HTTPS APIs, and the braintree endpoint is the only one that we see this behavior on, unfortunately, so I chalked it up to Braintree being more aggressive on their side closing sockets (and Hackney not noticing...)

It looks like we're still on Hackney 1.6.0 and our fork of braintree-elixir.  I wonder if bumping up to Hackney 1.6.1 might fix.  This PR might suggest a related fix:

https://github.com/benoitc/hackney/pull/308

**Comment by sorentwo** [comment]
Is anything keeping you on the fork of braintree-elixir? I'm curious if using the latest version (from master), with a bumped version of Hackney fixes the problem.

**Comment by nauger** [comment]
I _think_ just the PayPal PR.  The other bugs that I came across regarding XML and entities, it looks like you have cleaner fixes for.

**Comment by sorentwo** [comment]
@nauger I've released v0.6.0, if you'd like to try it out. It contains the PayPal PR, so everything should be set for you.

**Comment by nauger** [comment]
For the first time, I was actually able to get this error to occur in development (albeit, not on subsequent tries.)

This was on the most recent 0.6.0.

The hackney `1.6.1` is actually messed up on hex right now, I think.  Hex sees it as version 1.6.1, but the mix.exs file contained there-in is called 1.6.0.

**Comment by sorentwo** [comment]
Considering this a hackney pool issue and closing it.
