### ISSUE TITLE
XML parse failure with &amp; input

### ISSUE THREAD

**Issue by nauger** [sorentwo/braintree-elixir#23]
I haven't been able to pull a fix together yet, but I noticed the re-work for HTML entities does not take into account the `&amp`, as it decodes it to just `&` which then breaks the `:xmerl_scan.string`

```elixir
Braintree.XML.Decoder.load("<a><b type='string'>First &amp; Last</b></a>")
```

Demonstrates the issues

**Comment by sorentwo** [comment]
Closed by #24
