### ISSUE TITLE
:error, :unauthorized exception

### ISSUE THREAD

**Issue by samueljseay** [sorentwo/braintree-elixir#26]
So I've noticed there is an error case not being handled in any of the Braintree modules which is the "unauthorized" case, which returns `{:error, :unauthorized}` this, throws an exception since there isn't a valid match for it in any of the existing case conditions.

Was wondering how you want to handle this before I submit a PR? Would you like a large PR with a simple match like this added to every request with an error message? If so what would you like the error message to say?

Or perhaps its fine to throw an exception? But maybe we could throw a nicer one, that describes the problem instead of being a `CaseClauseError` exception?

**Comment by sorentwo** [comment]
I'm leaning heavily toward raising an exception in this case. It isn't something that we'd ever want/expect end users to handle during runtime, as you would from a `:not_found` error. If the request(s) are unauthorized something is wrong with the configuration and that needs to be fixed. 

`Braintree.UnauthorizedError` is the right approach IMO.

**Comment by sorentwo** [comment]
This is *finally* resolved with 46931d5!
