### ISSUE TITLE
Customer find function

### ISSUE THREAD

**Issue by tahmina8765** [sorentwo/braintree-elixir#27]
Is this function has implemented? I can not find any function in customer to get details with customer_id.

https://developers.braintreepayments.com/guides/customers/ruby#find

**Comment by sorentwo** [comment]
That function is definitely implemented:

https://github.com/sorentwo/braintree-elixir/blob/master/lib/customer.ex#L106
https://hexdocs.pm/braintree/Braintree.Customer.html#find/1
