### ISSUE TITLE
Valuable response information from Braintree API not returned

### ISSUE THREAD

**Issue by lau** [sorentwo/braintree-elixir#34]
When `Transaction.sale` is called and there is an error, the Braintree will return all kinds of information, including these codes: https://developers.braintreepayments.com/reference/general/processor-responses/authorization-responses

That information is available in the `api_error_response` here https://github.com/sorentwo/braintree-elixir/blob/197a903f5e7f87e37a0974f19db824678784b669/lib/transaction.ex#L141

However `Error.construct(error)` makes a struct that does not include that information. It would be useful if this library returned all of the information instead of throwing it away and just returning a `Braintree.ErrorResponse` without it.

**Comment by sorentwo** [comment]
@lau Thanks for the report! I've made a change in e7e0c54 that exposes the `transaction` key for `Braintree.ErrorResponse`, so all of the data should be available now.

**Comment by lau** [comment]
Thank you!
