### ISSUE TITLE
Failing tests for settlement

### ISSUE THREAD

**Issue by InoMurko** [sorentwo/braintree-elixir#40]
Tests like 
https://github.com/sorentwo/braintree-elixir/blob/5dd0616dbcda2287d0f5a450467c046757b23be9/test/integration/transaction_test.exs#L33
and 
https://github.com/sorentwo/braintree-elixir/blob/5dd0616dbcda2287d0f5a450467c046757b23be9/test/integration/transaction_test.exs#L10

are failing because the transaction immediately gets to status **settled**

**Comment by sorentwo** [comment]
Do you have steps to replicate the failure? I don't get any failures when I run the integration tests locally or on CI. The most trouble I've seen is from running too many tests simultaneously (i.e., in CI) where it gets rate limited.

If you have steps to replicate please post them or open a PR to fix things up.
