### ISSUE TITLE
0.9.0 Hex release?

### ISSUE THREAD

**Issue by doughsay** [sorentwo/braintree-elixir#49]
Hello!

It's been a while since 0.8.0 and some important fixes have been added. (I specifically need the binary to atom conversion for config.)  I'd like to stop pointing to master in my mix file.  Can we get a 0.9.0 release to hex please?

Thanks!

**Comment by doughsay** [comment]
Awesome, thanks!  I'm looking forward to 1.0 as well.

**Comment by sorentwo** [comment]
There are some specs that have started failing due to Braintree server changes. I'm fixing those up before the next release.

**Comment by sorentwo** [comment]
@doughsay Version 0.9.0 has been released with all of the accumulated changes. Thanks for the nudge!
