### ISSUE TITLE
Creating a merchant account always returns an 82607

### ISSUE THREAD

**Issue by gordoneliel** [sorentwo/braintree-elixir#50]
Creating a merchant account always returns as 82607 - Master merchant account ID is invalid.

**Comment by gordoneliel** [comment]
Solved: Braintree marketplace seems to have shutdown.

**Comment by sorentwo** [comment]
Really? I’ll check into that and modify the library accordingly. Thanks for the report.

**Comment by gordoneliel** [comment]
It is still being used by accounts that were grandfathered in according to this email I was sent when I asked about it:

Braintree has recently removed our Marketplace solutions off of our product line. Our Marketplace documentation is still public facing since we do have merchants who have been grandfathered into their Marketplace account. 

Our sandbox accounts no longer offer the ability to test a Marketplace integration, thus the issue you're running into. I do apologize for any inconvenience this may have caused. If you're still interested in using Marketplace, I can send you over to our Sales team and they can provide some additional information about PayPal's Marketplace solution.
