### ISSUE TITLE
Adding Telemetry events around the http calls?

### ISSUE THREAD

**Issue by aselder** [sorentwo/braintree-elixir#90]
We're using the Braintree library in our app and we're adding instrumentation. It would be really useful if the Braintree library would fire telemetry events on the http request, things like timing, repsonse code etc...

I'd be happy to whip up a PR if it would be considered for merging.

**Comment by sorentwo** [comment]
That's a wonderful idea! I'd love to add Telemetry integration. Please do open a PR.

**Comment by aselder** [comment]
I've put up the PR: https://github.com/sorentwo/braintree-elixir/pull/91

I hope it's useful.

**Comment by sorentwo** [comment]
Closing in favor of the PR.
